site_name: SimpleLogin Docs
site_url: https://simplelogin.io/docs/
site_description: Receive and send emails anonymously.
site_author: SimpleLogin

# Repository
repo_name: simple-login/documentation
repo_url: https://github.com/simple-login/documentation

copyright: Copyright &copy; 2019 - 2021 SimpleLogin

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Welcome: index.md
  - Getting started:
    - Register Account: getting-started/register-account.md
    - Create Aliases: getting-started/create-alias.md
    - Troubleshooting: getting-started/troubleshooting.md
  - Custom Domain:
    - Add a Custom Domain: custom-domain/add-domain.md
    - Manage your domain: custom-domain/manage-domain.md